#ifdef MY_INSTRUCTION
	MY_INSTRUCTION("ADD", INS_ADD)
	MY_INSTRUCTION("MOV", INS_MOV)
	MY_INSTRUCTION("LT", INS_LESS_THAN)
	MY_INSTRUCTION("LE", INS_LESS_EQUAL)
	MY_INSTRUCTION("GT", INS_GREATER_THAN)
	MY_INSTRUCTION("GE", INS_GREATER_EQUAL)



#endif

